version: '3.8'
services:
  mysql-db:
    image: mysql:8
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: onlinetutors
    ports:
      - "3308:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  onlinetutors:
    build: .
    container_name: onlinetutors
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/onlinetutors
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456
      SENDGRID_API_KEY: your_sendgrid_api_key_here

    depends_on:
      mysql-db:
        condition: service_healthy
    ports:
      - "8080:8080"
    volumes:
      - ./uploads:/app/uploads

